packageExtensions:
  "@babel/plugin-transform-react-display-name@*":
    dependencies:
      "@babel/core": ^7.20.12
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": ^7.20.12
  "@babel/plugin-transform-react-pure-annotations@*":
    dependencies:
      "@babel/core": ^7.20.12
  "@nrwl/react@15.6.2":
    dependencies:
      file-loader: ^6.2.0
  "@rollup/plugin-babel@*":
    dependencies:
      "@babel/core": ^7.20.12
  babel-loader@*:
    dependencies:
      "@babel/core": ^7.20.12
  babel-plugin-transform-async-to-promises@*:
    dependencies:
      "@babel/core": ^7.20.12

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.4.1.cjs
