pnpMode: loose

packageExtensions:
  "@nrwl/react@15.6.2":
    dependencies:
      file-loader: ^6.2.0
  babel-loader@*:
    dependencies:
      "@babel/core": "^7.20.12"
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "^7.20.12"
  "@babel/plugin-transform-react-display-name@*":
    dependencies:
      "@babel/core": "^7.20.12"
  "@babel/plugin-transform-react-pure-annotations@*":
    dependencies:
      "@babel/core": "^7.20.12"
  "@rollup/plugin-babel@*":
    dependencies:
      "@babel/core": "^7.20.12"
  "babel-plugin-transform-async-to-promises@*":
    dependencies:
      "@babel/core": "^7.20.12"
yarnPath: .yarn/releases/yarn-3.3.1.cjs
